import type { PlayerClass } from './classes';

/**
 * Placeholder palettes, read out of each hero's authored portrait.
 *
 * GENERATED by `scripts/extractHeroPalettes.mjs` — edit that, not this.
 *
 * Phase 2 builds hero placeholders from primitives, and the silhouette comes
 * from class crossed with tier: twenty-five combinations across sixty-five
 * heroes, so up to six heroes share an outline. Colour is what tells those six
 * apart, and taking it from the portrait means the thing a player recognises
 * on the battle line is the thing the artist drew — Kael Ironheart's green
 * gambeson, Lunara Frostweave's olive cloak, Titan Worldrender's purple.
 *
 * Hue is the artist's. Lightness and saturation are normalised into a band
 * that reads on a lit mesh, because the portraits are dark moody paintings and
 * their literal mean colour sits around twelve percent lightness — a material
 * that colour is indistinguishable from the shadow it stands in.
 */

export interface HeroPalette {
  /** The identity colour: clothing, cloak or armour trim. */
  accent: string;
  /** A second distinct hue from the same portrait, for secondary volumes. */
  secondary: string;
  /** 1 to 5. Drives how elaborate the placeholder is; see heroSilhouettes.ts. */
  tier: number;
}

export const HERO_PALETTES: Record<string, HeroPalette> = {
  h1: { accent: '#a25e35', secondary: '#4b9b3b', tier: 1 },
  h2: { accent: '#ae653c', secondary: '#9b8a3b', tier: 1 },
  h3: { accent: '#a05a36', secondary: '#969b3b', tier: 1 },
  h4: { accent: '#a55a31', secondary: '#959b3b', tier: 1 },
  h5: { accent: '#a15d35', secondary: '#9b893b', tier: 1 },
  h6: { accent: '#a45b32', secondary: '#999b3b', tier: 1 },
  h7: { accent: '#9b633b', secondary: '#3b639b', tier: 1 },
  h8: { accent: '#a05c36', secondary: '#3b8a9b', tier: 1 },
  h9: { accent: '#b66b39', secondary: '#cab572', tier: 1 },
  h10: { accent: '#af6637', secondary: '#3975a2', tier: 1 },
  h11: { accent: '#b46635', secondary: '#9a9b3b', tier: 1 },
  h12: { accent: '#a35833', secondary: '#9b873b', tier: 1 },
  h13: { accent: '#a15a35', secondary: '#3b9b8b', tier: 1 },
  h14: { accent: '#9f5d37', secondary: '#5743c5', tier: 1 },
  h15: { accent: '#b96939', secondary: '#979b3b', tier: 1 },
  h16: { accent: '#9e6038', secondary: '#979b3b', tier: 1 },
  h17: { accent: '#9b613b', secondary: '#4a9b3b', tier: 1 },
  h18: { accent: '#a35b33', secondary: '#959b3b', tier: 1 },
  h19: { accent: '#a05a36', secondary: '#969b3b', tier: 1 },
  h20: { accent: '#a15a35', secondary: '#9b8c3b', tier: 1 },
  h21: { accent: '#ae6a42', secondary: '#3b9b48', tier: 1 },
  h22: { accent: '#a15c36', secondary: '#3b799b', tier: 1 },
  h23: { accent: '#b36532', secondary: '#f0d94c', tier: 1 },
  h24: { accent: '#9f5f37', secondary: '#3fa697', tier: 1 },
  h25: { accent: '#b06440', secondary: '#959b3b', tier: 1 },
  h26: { accent: '#a55e31', secondary: '#999b3b', tier: 1 },
  h27: { accent: '#a05c37', secondary: '#949b3b', tier: 1 },
  h28: { accent: '#a46032', secondary: '#969b3b', tier: 1 },
  h29: { accent: '#a55c31', secondary: '#939b3b', tier: 1 },
  h30: { accent: '#a15f36', secondary: '#979b3b', tier: 1 },
  h31: { accent: '#c16b33', secondary: '#af2732', tier: 2 },
  h32: { accent: '#c0642f', secondary: '#c61043', tier: 2 },
  h33: { accent: '#bd6133', secondary: '#c61020', tier: 2 },
  h34: { accent: '#e06112', secondary: '#f0d24c', tier: 2 },
  h35: { accent: '#ca6631', secondary: '#f0d64c', tier: 2 },
  h36: { accent: '#a04836', secondary: '#bc8135', tier: 2 },
  h37: { accent: '#3e2ea8', secondary: '#d79265', tier: 2 },
  h38: { accent: '#c34a34', secondary: '#1050c6', tier: 2 },
  h39: { accent: '#dd5f12', secondary: '#c6101c', tier: 2 },
  h40: { accent: '#c6102f', secondary: '#f0b14c', tier: 2 },
  h41: { accent: '#a14736', secondary: '#1359e8', tier: 3 },
  h42: { accent: '#cc4731', secondary: '#f0da4c', tier: 3 },
  h43: { accent: '#b34b3f', secondary: '#f0b84c', tier: 3 },
  h44: { accent: '#a53c31', secondary: '#ae32c2', tier: 3 },
  h45: { accent: '#2bab7e', secondary: '#4834c4', tier: 3 },
  h46: { accent: '#aa2c3e', secondary: '#30a67a', tier: 3 },
  h47: { accent: '#652cbd', secondary: '#e41363', tier: 3 },
  h48: { accent: '#1056c6', secondary: '#10c6b5', tier: 3 },
  h49: { accent: '#e3123a', secondary: '#c66b32', tier: 3 },
  h50: { accent: '#d88d65', secondary: '#c82838', tier: 3 },
  h51: { accent: '#a53d32', secondary: '#f0dc4c', tier: 4 },
  h52: { accent: '#2b59ab', secondary: '#f0d54c', tier: 4 },
  h53: { accent: '#aa2c3d', secondary: '#f0d94c', tier: 4 },
  h54: { accent: '#a2355e', secondary: '#7a10c6', tier: 4 },
  h55: { accent: '#3145a5', secondary: '#d4ae68', tier: 4 },
  h56: { accent: '#5910c6', secondary: '#f0da4c', tier: 4 },
  h57: { accent: '#4cdcf0', secondary: '#f0d94c', tier: 4 },
  h58: { accent: '#e42e13', secondary: '#f0b04c', tier: 4 },
  h59: { accent: '#be4834', secondary: '#c6104f', tier: 4 },
  h60: { accent: '#f0b64c', secondary: '#4434a2', tier: 4 },
  h61: { accent: '#752ea8', secondary: '#4cbef0', tier: 5 },
  h62: { accent: '#3769bf', secondary: '#aa2d5e', tier: 5 },
  h63: { accent: '#ca4337', secondary: '#f08a4c', tier: 5 },
  h64: { accent: '#4ce1f0', secondary: '#1335e5', tier: 5 },
  h65: { accent: '#b76a36', secondary: '#f0d44c', tier: 5 },
};

/** Neutral fall-back for a hero id with no portrait on record. */
export const DEFAULT_HERO_PALETTE: HeroPalette = { accent: '#8a8f98', secondary: '#5d6068', tier: 1 };

export function getHeroPalette(heroId: string): HeroPalette {
  return HERO_PALETTES[heroId] ?? DEFAULT_HERO_PALETTE;
}

/** Every class a placeholder can be built for, for exhaustiveness checks. */
export const PLACEHOLDER_CLASSES: readonly PlayerClass[] = ['warrior', 'berserker', 'archer', 'mage', 'monk'];
