import { StyleSheet } from 'react-native';
import { theme } from '../../theme/colors';

export const styles = StyleSheet.create({
  achievementsTab: {
    gap: 8,
    position: 'relative',
    overflow: 'hidden',
  },
  achievementsAtmosphere: {
    ...StyleSheet.absoluteFillObject,
    zIndex: -1,
  },
  achievementsAtmosphereNoise: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.14,
  },
  achievementsAtmosphereOrbPrimary: {
    position: 'absolute',
    top: -90,
    left: -60,
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: 'rgba(82, 135, 191, 0.18)',
  },
  achievementsAtmosphereOrbSecondary: {
    position: 'absolute',
    right: -40,
    top: 140,
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: 'rgba(128, 94, 163, 0.16)',
  },
  achievementsAtmosphereGrid: {
    ...StyleSheet.absoluteFillObject,
    borderWidth: 1,
    borderColor: 'rgba(140, 176, 219, 0.06)',
    borderRadius: 14,
  },

  // ── Bonus Card ───────────────────────────────────────────
  achievementBonusCard: {
    position: 'relative',
    overflow: 'hidden',
    backgroundColor: '#17232B',
    borderWidth: 1,
    borderColor: '#385A66',
    borderRadius: 8,
    padding: 10,
    marginBottom: 10,
  },
  achievementBonusArt: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.14,
  },
  achievementBonusScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(7, 13, 21, 0.5)',
  },
  achievementBonusHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  achievementBonusTitle: {
    fontSize: 12,
    color: '#D5F2FF',
    fontWeight: '700',
  },
  achievementBonusValue: {
    fontSize: 14,
    color: '#7EE2A9',
    fontWeight: '800',
  },
  achievementBonusDesc: {
    fontSize: 10,
    color: '#A6C8D4',
    lineHeight: 15,
  },
  achievementOverviewGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
  },
  achievementOverviewCard: {
    flex: 1,
    minWidth: 108,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#325262',
    backgroundColor: '#10202A',
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  achievementOverviewLabel: {
    fontSize: 9,
    fontWeight: '800',
    color: '#8FB7C5',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  achievementOverviewValue: {
    fontSize: 16,
    fontWeight: '800',
    color: '#E6F5FF',
    marginBottom: 2,
  },
  achievementOverviewHint: {
    fontSize: 10,
    color: '#98BCCC',
  },
  achievementQuickGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 10,
  },
  achievementQuickCard: {
    flexGrow: 1,
    minWidth: 150,
    backgroundColor: '#151A2A',
    borderWidth: 1,
    borderColor: '#374069',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 10,
  },
  achievementQuickTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: '#E8E8FF',
    marginBottom: 3,
  },
  achievementQuickBody: {
    fontSize: 10,
    color: '#A9B2DA',
    lineHeight: 15,
  },

  // ── Claim All ────────────────────────────────────────────
  claimAllRow: {
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  claimAllInfo: {
    fontSize: 10,
    color: '#B5D5E5',
    fontWeight: '700',
  },
  claimAllBtn: {
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#6DA98B',
    backgroundColor: '#264A3A',
    paddingVertical: 5,
    paddingHorizontal: 9,
  },
  claimAllBtnDisabled: {
    opacity: 0.5,
  },
  claimAllBtnText: {
    fontSize: 10,
    color: '#DBFFEC',
    fontWeight: '700',
  },

  // ── Weekly Event ─────────────────────────────────────────
  weeklyEventCard: {
    backgroundColor: '#121f2e',
    borderWidth: 1,
    borderColor: '#2f4d71',
    borderRadius: 8,
    padding: 10,
    marginBottom: 10,
  },
  weeklyEventTitle: {
    fontSize: 12,
    color: '#DCEFFF',
    fontWeight: '700',
    marginBottom: 4,
  },
  weeklyEventDesc: {
    fontSize: 10,
    color: '#AFC5DD',
    marginBottom: 8,
    lineHeight: 15,
  },
  weeklyProgressLabel: {
    fontSize: 11,
    color: '#90D0FF',
    marginBottom: 6,
    fontWeight: '700',
  },
  weeklyTrackRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 5,
  },
  weeklyTrackText: {
    fontSize: 11,
    color: '#D2E0F0',
  },
  weeklyClaimBtn: {
    backgroundColor: '#2e6948',
    borderWidth: 1,
    borderColor: '#5ea280',
    borderRadius: 4,
    paddingVertical: 4,
    paddingHorizontal: 10,
  },
  weeklyClaimBtnDisabled: {
    opacity: 0.45,
  },
  weeklyClaimBtnText: {
    fontSize: 10,
    color: '#d8ffeb',
    fontWeight: '700',
  },

  // ── Mission Board ────────────────────────────────────────
  missionBoardCard: {
    position: 'relative',
    overflow: 'hidden',
    backgroundColor: '#1A182B',
    borderWidth: 1,
    borderColor: '#3A3161',
    borderRadius: 8,
    padding: 10,
    marginBottom: 10,
  },
  missionBoardArt: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.12,
  },
  missionBoardScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(10, 8, 24, 0.56)',
  },
  missionGroupCard: {
    backgroundColor: '#151327',
    borderWidth: 1,
    borderColor: '#342C58',
    borderRadius: 10,
    padding: 10,
    marginBottom: 8,
  },
  missionGroupHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  missionGroupTitle: {
    fontSize: 11,
    fontWeight: '800',
    color: '#F1E9FF',
  },
  missionGroupMeta: {
    fontSize: 10,
    color: '#A6B7E9',
    fontWeight: '700',
  },
  missionGroupFlavor: {
    fontSize: 10,
    color: '#A49DCB',
    marginBottom: 4,
  },
  missionRow: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#3A3260',
    backgroundColor: '#191533',
    marginBottom: 6,
  },
  missionStateRail: {
    width: 3,
    alignSelf: 'stretch',
    borderRadius: 99,
    backgroundColor: '#546A8A',
  },
  missionStateRailDone: {
    backgroundColor: '#62D7A5',
  },
  missionTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  missionInfo: {
    flex: 1,
  },
  missionTitle: {
    fontSize: 11,
    color: '#E3DBFF',
    fontWeight: '700',
    marginBottom: 2,
  },
  missionDesc: {
    fontSize: 10,
    color: '#B7ADDC',
    marginBottom: 2,
  },
  missionProgress: {
    fontSize: 10,
    color: '#8ED5FF',
    fontWeight: '700',
    marginBottom: 3,
  },
  missionChip: {
    fontSize: 9,
    fontWeight: '800',
    color: '#D3E7FF',
    backgroundColor: '#2A355A',
    borderWidth: 1,
    borderColor: '#5165A5',
    borderRadius: 999,
    paddingVertical: 3,
    paddingHorizontal: 7,
    overflow: 'hidden',
  },
  missionProgressBarBg: {
    height: 6,
    borderRadius: 99,
    backgroundColor: '#2D2947',
    overflow: 'hidden',
  },
  missionProgressBarFill: {
    height: '100%',
    borderRadius: 99,
    backgroundColor: '#6CB8FF',
  },
  missionClaimBtn: {
    backgroundColor: '#3B3D73',
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#7C82D3',
    paddingVertical: 5,
    paddingHorizontal: 10,
  },
  missionClaimBtnDisabled: {
    opacity: 0.45,
  },
  missionClaimBtnText: {
    fontSize: 10,
    color: '#E8E9FF',
    fontWeight: '700',
  },

  // ── Achievement Cards ────────────────────────────────────
  achCard: {
    position: 'relative',
    overflow: 'hidden',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 10,
    paddingHorizontal: 10,
    backgroundColor: '#121B28',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#2A4257',
    marginBottom: 8,
    opacity: 0.6,
  },
  recordPlaqueArt: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.13,
  },
  recordPlaqueScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(8, 12, 20, 0.54)',
  },
  recordStateRail: {
    width: 3,
    alignSelf: 'stretch',
    borderRadius: 99,
    backgroundColor: '#4E657A',
  },
  recordStateRailUnlocked: {
    backgroundColor: '#6ED59C',
  },
  achCardUnlocked: {
    opacity: 1,
    borderColor: '#68D69D',
    backgroundColor: '#152723',
  },
  achEmoji: {
    fontSize: 20,
  },
  achCardInfo: {
    flex: 1,
  },
  recordTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  achName: {
    fontSize: 12,
    fontWeight: '600',
    color: '#95A8B7',
    marginBottom: 2,
  },
  recordStateChip: {
    fontSize: 9,
    fontWeight: '800',
    color: '#BDD1E0',
    backgroundColor: '#223244',
    borderWidth: 1,
    borderColor: '#3E556A',
    borderRadius: 999,
    paddingVertical: 3,
    paddingHorizontal: 7,
    overflow: 'hidden',
  },
  recordStateChipUnlocked: {
    color: '#D8FFEC',
    backgroundColor: '#1F4A36',
    borderColor: '#4E9170',
  },
  achNameUnlocked: {
    color: '#EDFFF6',
  },
  achDesc: {
    fontSize: 10,
    color: '#8DA3B5',
  },
  achBonusLine: {
    marginTop: 3,
    fontSize: 10,
    color: '#8CB2C4',
    fontWeight: '700',
  },
  achBonusLineUnlocked: {
    color: '#79D89F',
  },
  recordsFilterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 10,
  },
  recordsFilterChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#335168',
    backgroundColor: '#101D2A',
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  recordsFilterChipActive: {
    borderColor: '#6FC7A2',
    backgroundColor: '#193229',
  },
  recordsFilterChipText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#A0BED3',
  },
  recordsFilterChipTextActive: {
    color: '#E8FFF3',
  },

  // ── Collection ───────────────────────────────────────────
  collectionCard: {
    position: 'relative',
    overflow: 'hidden',
    backgroundColor: '#111E2C',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#2A4260',
    padding: 10,
    marginBottom: 8,
  },
  collectionVaultArt: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.12,
  },
  collectionVaultScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(7, 13, 21, 0.52)',
  },
  collectionCardTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#DAEEFF',
    marginBottom: 6,
  },
  collectionStat: {
    fontSize: 11,
    color: '#9BB6CC',
    marginBottom: 2,
  },
  collectionBonus: {
    fontSize: 10,
    color: '#7DFF9A',
    marginTop: 3,
    fontWeight: '700',
  },
  collectionHint: {
    fontSize: 10,
    color: '#AA8855',
    marginTop: 3,
    fontStyle: 'italic',
  },
  collectionProgressRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 4,
  },
  collectionProgressLabel: {
    fontSize: 10,
    color: '#9BB6CC',
    fontWeight: '700',
  },
  collectionProgressValue: {
    fontSize: 10,
    color: '#D9EDFF',
    fontWeight: '700',
  },
  collectionProgressBarBg: {
    height: 10,
    borderRadius: 999,
    backgroundColor: '#1A3042',
    overflow: 'hidden',
  },
  collectionProgressBarFill: {
    height: '100%',
    backgroundColor: '#63D7A1',
    borderRadius: 999,
  },
  collectionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 8,
  },
  collectionCardCompact: {
    position: 'relative',
    overflow: 'hidden',
    flex: 1,
    minWidth: 112,
    backgroundColor: '#111E2C',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#2A4260',
    padding: 10,
  },
  collectionVaultArtCompact: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.1,
  },
  collectionVaultScrimCompact: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(8, 13, 22, 0.48)',
  },
  unlockChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  unlockChip: {
    fontSize: 10,
    fontWeight: '700',
    color: '#D2F8E1',
    backgroundColor: '#1D3B2E',
    borderWidth: 1,
    borderColor: '#3E7A5E',
    borderRadius: 999,
    paddingVertical: 5,
    paddingHorizontal: 9,
    overflow: 'hidden',
  },

  // ── Story ────────────────────────────────────────────────
  storyCardWrap: {
    backgroundColor: '#111E2B',
    borderWidth: 1,
    borderColor: '#28465F',
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
  },
  storyCardTitle: {
    color: '#EAF3FF',
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 4,
  },
  storyCardSubtitle: {
    color: '#9DB4C9',
    fontSize: 11,
    marginBottom: 8,
  },
  storyBeatCard: {
    backgroundColor: '#0D1722',
    borderWidth: 1,
    borderColor: '#243A4E',
    borderRadius: 8,
    padding: 10,
    marginBottom: 8,
  },
  storyBeatCardUnlocked: {
    borderColor: '#3B6A8E',
    backgroundColor: '#132636',
  },
  storyBeatChapter: {
    color: '#AFC6DA',
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 4,
  },
  storyBeatChapterUnlocked: {
    color: '#D8ECFF',
  },
  storyBeatBody: {
    color: '#C7D8E7',
    fontSize: 11,
    lineHeight: 16,
  },
  storyBeatReq: {
    color: '#8FA7BC',
    fontSize: 10,
    marginTop: 6,
  },
  storyNextHint: {
    color: '#FFE4A8',
    fontSize: 11,
    fontWeight: '700',
    marginTop: 4,
  },

  // ── Codex ────────────────────────────────────────────────
  codexOverviewRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  codexOverviewCard: {
    flex: 1,
    minWidth: 112,
    backgroundColor: '#101A27',
    borderWidth: 1,
    borderColor: '#2B435B',
    borderRadius: 12,
    padding: 12,
  },
  codexOverviewCardPrimary: {
    backgroundColor: '#131D2E',
    borderColor: '#47617D',
  },
  codexOverviewEyebrow: {
    fontSize: 10,
    fontWeight: '800',
    color: '#8FB0CC',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  codexOverviewValue: {
    fontSize: 20,
    fontWeight: '800',
    color: '#F4F8FF',
    marginBottom: 4,
  },
  codexOverviewBody: {
    fontSize: 11,
    color: '#9CB4CA',
    lineHeight: 16,
  },
  codexSectionShell: {
    backgroundColor: '#0D1622',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#23384D',
    padding: 12,
    marginBottom: 12,
  },
  codexSectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
    marginBottom: 12,
  },
  codexSectionHeaderCopy: {
    flex: 1,
  },
  codexSectionKicker: {
    fontSize: 10,
    fontWeight: '800',
    color: '#8EA8C0',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  codexSectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#F3F8FF',
    marginBottom: 4,
  },
  codexSectionDescription: {
    fontSize: 11,
    color: '#98B0C7',
    lineHeight: 17,
  },
  codexSectionBadge: {
    minWidth: 88,
    backgroundColor: '#111E2D',
    borderWidth: 1,
    borderColor: '#2E4963',
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 10,
    alignItems: 'center',
  },
  codexSectionBadgeValue: {
    fontSize: 18,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  codexSectionBadgeLabel: {
    fontSize: 10,
    color: '#96AFC7',
    textAlign: 'center',
  },
  codexFilterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  codexFilterChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#334B63',
    backgroundColor: '#101C2A',
    paddingVertical: 7,
    paddingHorizontal: 12,
  },
  codexFilterChipActive: {
    borderColor: '#6DA4D9',
    backgroundColor: '#16314C',
  },
  codexFilterChipText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#98B2CA',
  },
  codexFilterChipTextActive: {
    color: '#E7F3FF',
  },
  codexSpotlightCard: {
    flexDirection: 'row',
    gap: 12,
    backgroundColor: '#101C2A',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2D465E',
    padding: 12,
    marginBottom: 12,
  },
  codexSpotlightMedia: {
    width: 76,
    alignItems: 'center',
    justifyContent: 'center',
  },
  codexClassifiedPortrait: {
    width: 64,
    height: 64,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#41566F',
    backgroundColor: '#0A121C',
    alignItems: 'center',
    justifyContent: 'center',
  },
  codexClassifiedPortraitText: {
    fontSize: 28,
    fontWeight: '800',
    color: '#6D849A',
  },
  codexSpotlightBody: {
    flex: 1,
  },
  codexSpotlightHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 8,
    marginBottom: 8,
  },
  codexSpotlightTitleWrap: {
    flex: 1,
  },
  codexSpotlightEyebrow: {
    fontSize: 10,
    fontWeight: '800',
    color: '#8DB2D8',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 3,
  },
  codexSpotlightTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: '#F3F8FF',
  },
  codexTierBadge: {
    borderRadius: 999,
    borderWidth: 1,
    paddingVertical: 5,
    paddingHorizontal: 8,
  },
  codexTierBadgeText: {
    fontSize: 10,
    fontWeight: '800',
  },
  codexMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 8,
  },
  codexMetaChip: {
    fontSize: 10,
    fontWeight: '700',
    color: '#C2D6EA',
    backgroundColor: '#152537',
    borderWidth: 1,
    borderColor: '#2B445C',
    borderRadius: 999,
    paddingVertical: 4,
    paddingHorizontal: 8,
    overflow: 'hidden',
  },
  codexSpotlightDescription: {
    fontSize: 11,
    color: '#A7BDD2',
    lineHeight: 17,
    marginBottom: 10,
  },
  codexRelicInlineCard: {
    backgroundColor: '#0F1B28',
    borderWidth: 1,
    borderColor: '#2A4560',
    borderRadius: 10,
    padding: 10,
    marginBottom: 10,
  },
  codexRelicInlineLabel: {
    fontSize: 10,
    fontWeight: '800',
    color: '#8DB2D8',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 4,
  },
  codexRelicInlineName: {
    fontSize: 12,
    fontWeight: '800',
    color: '#F0F6FF',
    marginBottom: 2,
  },
  codexRelicInlineMeta: {
    fontSize: 10,
    color: '#9BB6CD',
    lineHeight: 15,
    marginBottom: 4,
  },
  codexRelicInlineDesc: {
    fontSize: 10,
    color: '#B2C8DB',
    lineHeight: 15,
  },
  codexSpotlightActionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 8,
  },
  codexActionPrimary: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#7D6942',
    backgroundColor: '#3B2D14',
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  codexActionPrimaryText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#FFE5A0',
  },
  codexActionSecondary: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#43658A',
    backgroundColor: '#18324A',
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  codexActionSecondaryText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#D9ECFF',
  },
  codexActionHint: {
    fontSize: 10,
    color: '#91A8BC',
    fontWeight: '700',
  },
  codexGalleryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  codexGalleryCard: {
    minWidth: 92,
    backgroundColor: '#101825',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#263C52',
    padding: 8,
  },
  codexGalleryCardUnlocked: {
    backgroundColor: '#111D2A',
  },
  codexGalleryCardSelected: {
    borderColor: '#74AEE7',
    backgroundColor: '#15283C',
  },
  codexGalleryPortraitWrap: {
    position: 'relative',
    height: 66,
    borderRadius: 10,
    borderWidth: 1,
    backgroundColor: '#0C131D',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
    overflow: 'hidden',
  },
  codexGalleryLockedPortrait: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0A121A',
  },
  codexGalleryLockedPortraitText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#687E92',
    letterSpacing: 0.8,
  },
  codexGalleryName: {
    fontSize: 11,
    fontWeight: '700',
    color: '#EEF5FF',
    marginBottom: 3,
  },
  codexGalleryMeta: {
    fontSize: 10,
    color: '#8EA6BC',
    lineHeight: 14,
  },
  codexGalleryRelicState: {
    marginTop: 4,
    fontSize: 10,
    color: '#A8C2D9',
    fontWeight: '700',
  },
  codexRelicSpotlightCard: {
    backgroundColor: '#101B29',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2E4962',
    padding: 12,
    marginBottom: 12,
  },
  codexRelicSpotlightHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 8,
    marginBottom: 8,
  },
  codexRelicHeroLine: {
    fontSize: 11,
    color: '#9FB6CB',
    marginTop: 4,
  },
  codexRelicGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  codexRelicCard: {
    minWidth: 140,
    backgroundColor: '#0F1823',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#273E54',
    padding: 10,
  },
  codexRelicCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  codexRelicIconWrap: {
    position: 'relative',
    width: 42,
    height: 42,
    borderRadius: 10,
    borderWidth: 1,
    backgroundColor: '#0A111A',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  codexRelicRankPill: {
    borderRadius: 999,
    backgroundColor: '#1B3147',
    borderWidth: 1,
    borderColor: '#3C6388',
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  codexRelicRankText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#D9ECFF',
  },
  codexRelicCardTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: '#F4F8FF',
    marginBottom: 4,
    lineHeight: 16,
  },
  codexRelicCardMeta: {
    fontSize: 10,
    color: '#93AABF',
    lineHeight: 14,
  },
  storyNodeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  storyNode: {
    flexGrow: 1,
    minWidth: 112,
    backgroundColor: '#101A27',
    borderWidth: 1,
    borderColor: '#23384D',
    borderRadius: 12,
    padding: 10,
  },
  storyNodeUnlocked: {
    backgroundColor: '#142536',
    borderColor: '#4273A1',
  },
  storyNodeSelected: {
    borderColor: '#8DC5FF',
    backgroundColor: '#183149',
  },
  storyNodeChapter: {
    fontSize: 10,
    fontWeight: '800',
    color: '#96AFCA',
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  storyNodeTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: '#F0F6FF',
    lineHeight: 15,
    marginBottom: 6,
  },
  storyNodeState: {
    fontSize: 10,
    color: '#A7BED3',
  },
  masteryTitleGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  masteryTitleCard: {
    flexGrow: 1,
    minWidth: 136,
    backgroundColor: '#0F1824',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#273E54',
    padding: 10,
  },
  masteryTitleCardDone: {
    backgroundColor: '#15251C',
    borderColor: '#4D8D67',
  },
  masteryTitleState: {
    fontSize: 9,
    fontWeight: '800',
    color: '#91A9BF',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 4,
  },
  masteryTitleName: {
    fontSize: 14,
    fontWeight: '800',
    color: '#F1F7FF',
    marginBottom: 4,
  },
  masteryTitleNameDone: {
    color: '#7DFF9A',
  },
  masteryTitleDesc: {
    fontSize: 10,
    color: '#A1B9CD',
    lineHeight: 15,
    marginBottom: 6,
  },
  masteryTitleReward: {
    fontSize: 10,
    fontWeight: '700',
    color: '#FFD88A',
  },
  codexEntry: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingVertical: 8,
    paddingHorizontal: 8,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#2A3C55',
    backgroundColor: '#0F1A28',
    marginBottom: 6,
    opacity: 0.6,
  },
  codexEntryDone: {
    opacity: 1,
    borderColor: '#4A8E6A',
    backgroundColor: '#122218',
  },
  codexEntryLeft: {
    flex: 1,
  },
  codexHeroIconBtn: {
    position: 'relative',
    marginRight: 8,
  },
  codexClaimDot: {
    position: 'absolute',
    top: -3,
    right: -3,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#ff3b30',
    borderWidth: 1,
    borderColor: theme.text.primary,
  },
  codexHeroPortrait: {
    width: 28,
    height: 28,
    borderRadius: 3,
  },
  codexHeroPortraitMedium: {
    width: 42,
    height: 42,
    borderRadius: 8,
  },
  codexHeroPortraitLarge: {
    width: 64,
    height: 64,
    borderRadius: 10,
  },
  codexHeroEmojiMedium: {
    fontSize: 26,
  },
  codexHeroEmojiLarge: {
    fontSize: 40,
  },
  codexTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#A0C0DD',
    marginBottom: 2,
  },
  codexTitleDone: {
    color: '#7DFF9A',
  },
  codexDesc: {
    fontSize: 10,
    color: '#7A9BB5',
    marginBottom: 2,
  },
  codexReward: {
    fontSize: 10,
    color: '#FFD88A',
    fontWeight: '700',
  },

  // ── Toggle / Shared ──────────────────────────────────────
  toggleBtn: {
    paddingVertical: 5,
    paddingHorizontal: 10,
    backgroundColor: '#4A4A7A',
    borderRadius: 4,
  },
  toggleBtnText: {
    fontSize: 11,
    fontWeight: '700',
    color: theme.text.primary,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: theme.text.primary,
    marginBottom: 8,
  },
  sectionHelperText: {
    fontSize: 10,
    color: '#98b2c8',
    marginBottom: 8,
  },

  // ── Hero Portrait Viewer Modal ───────────────────────────
  portraitModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  portraitModalContent: {
    backgroundColor: '#111A26',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2A4A6B',
    padding: 20,
    alignItems: 'center',
    maxWidth: 320,
    width: '85%',
  },
  portraitModalImage: {
    width: 240,
    height: 240,
    borderRadius: 8,
    marginBottom: 16,
  },
  portraitModalEmoji: {
    fontSize: 80,
    marginBottom: 16,
  },
  portraitModalName: {
    fontSize: 18,
    fontWeight: '800',
    color: '#F6F8FF',
    marginBottom: 4,
    textAlign: 'center',
  },
  portraitModalTier: {
    fontSize: 13,
    fontWeight: '600',
    color: '#FFD700',
    marginBottom: 2,
  },
  portraitModalClass: {
    fontSize: 12,
    fontWeight: '600',
    color: '#7A9BB5',
    marginBottom: 10,
    textTransform: 'capitalize',
  },
  portraitModalBackstory: {
    fontSize: 12,
    color: '#A0C0DD',
    textAlign: 'center',
    lineHeight: 18,
    marginBottom: 12,
  },
  portraitModalWeaponName: {
    fontSize: 13,
    fontWeight: '800',
    color: '#FFD88A',
    textAlign: 'center',
    marginBottom: 6,
  },
  portraitModalWeaponSkill: {
    fontSize: 11,
    color: '#B4C8DC',
    textAlign: 'center',
    lineHeight: 16,
    marginBottom: 16,
  },
  portraitModalCloseBtn: {
    backgroundColor: '#1C2E42',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 32,
    borderWidth: 1,
    borderColor: '#385A66',
  },
  portraitModalCloseBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#A0C0DD',
  },
});
